"""Shared types and enums for wireviz models."""

from wireviz.models.dataclasses import (  # noqa: F401
    AUTOGENERATED_PREFIX,
    BomCategory,
    Designator,
    NoneOrMorePinIndices,
    NoneOrMorePins,
    OneOrMoreWires,
    Pin,
    PinIndex,
    PlainText,
    QtyMultiplierCable,
    QtyMultiplierConnector,
    Side,
    Wire,
)

